### ISSUE TITLE
断链localhost问题

### ISSUE THREAD

**Issue by ghost** [lhccong/short-link-dog-backend#1]
为什么生成的短链是域名是localhost哇？？

![image](https://github.com/user-attachments/assets/20d1585b-f4bd-4561-af8a-e983c2321cda)

**Comment by lhccong** [comment]
因为短链的地址就是你后台服务的地址，本地部署就只能是localhost了，当后端服务上线就可以换成你的服务器域名地址

**Comment by ghost** [comment]
> 因为短链的地址就是你后台服务的地址，本地部署就只能是localhost了，当后端服务上线就可以换成你的服务器域名地址

我这里就是直接在你上线的平台实验的。

![image](https://github.com/user-attachments/assets/af7df844-d555-4883-a0fb-9df141caada7)

**Comment by lhccong** [comment]
是的，已修复感谢
